### ISSUE TITLE
when running a batch prediction, predictions.csv can be incomplete

### ISSUE THREAD

**Issue by devTristan** [bigmlcom/bigmler#147]
Ran a batch prediction on 50k rows. This usually works. Got an incomplete predictions.csv file back, despite no complaints from bigmler. It exited with code 0 and appeared to work fine. The file was cut off after about 10k records, halfway through a line.

My guess is that it should catch any errors and retry.

**Comment by mmerce** [comment]
I'm trying to reproduce that. I'll let you know.

**Comment by devTristan** [comment]
I've run a few hundred batch predictions and only gotten it the once.

**Comment by mmerce** [comment]
Probably this will be due to a transient connection problem, and I've not been able to reproduce it. Moreover, some people complain about similar things happening with the `requests` library with no error indicator appearing. I'll try to produce a sounder version checking the `content-length` header.

**Comment by devTristan** [comment]
Thanks :)

**Comment by mmerce** [comment]
Please, check the version 3.3.1 of bigmler that includes a new bindings version checking `content-length` header.

**Comment by devTristan** [comment]
Will do, and I'll come back if I experience the issue again.

**Comment by mmerce** [comment]
Closing this issue. If you experience the issue again, please reopen.
